#! /bin/python3

#you are asked to ensure that the first and last names of people begin with a capital letter in their passports

import math
import os
import random
import re
import sys

#Complete the solve function below.
def solve(s):

    import string
    return(string.capwords(input(), ' '))

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(results + '\n')

    fptr.close()
